// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfIdGgQn5C9HViFJtRx9J3X-z6MoDmDBc',
    appId: '1:95843929929:web:32478692a6aa12852a5498',
    messagingSenderId: '95843929929',
    projectId: 'app-mecanica-newtoniana',
    authDomain: 'app-mecanica-newtoniana.firebaseapp.com',
    storageBucket: 'app-mecanica-newtoniana.firebasestorage.app',
    measurementId: 'G-TH5F0M4XBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8JoOTP6qYHD1taK5Q2ma9XmpjOTVAVy4',
    appId: '1:95843929929:android:065de4e030f7c62a2a5498',
    messagingSenderId: '95843929929',
    projectId: 'app-mecanica-newtoniana',
    storageBucket: 'app-mecanica-newtoniana.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGzU9Mh9jPKWQW_geq5SF3i9ErTnzPa3s',
    appId: '1:95843929929:ios:d6f007ea0e70a01f2a5498',
    messagingSenderId: '95843929929',
    projectId: 'app-mecanica-newtoniana',
    storageBucket: 'app-mecanica-newtoniana.firebasestorage.app',
    iosBundleId: 'com.example.appMecanica',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGzU9Mh9jPKWQW_geq5SF3i9ErTnzPa3s',
    appId: '1:95843929929:ios:d6f007ea0e70a01f2a5498',
    messagingSenderId: '95843929929',
    projectId: 'app-mecanica-newtoniana',
    storageBucket: 'app-mecanica-newtoniana.firebasestorage.app',
    iosBundleId: 'com.example.appMecanica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfIdGgQn5C9HViFJtRx9J3X-z6MoDmDBc',
    appId: '1:95843929929:web:60b9b56b2bd65f602a5498',
    messagingSenderId: '95843929929',
    projectId: 'app-mecanica-newtoniana',
    authDomain: 'app-mecanica-newtoniana.firebaseapp.com',
    storageBucket: 'app-mecanica-newtoniana.firebasestorage.app',
    measurementId: 'G-JHXM9RC1P3',
  );
}
